# Generated by Django 3.1 on 2020-08-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailrecord",
            old_name="updateted_date",
            new_name="updated_date",
        ),
    ]
